#!/bin/bash
#
#SBATCH -p hpc-bio-pascal
#SBATCH --chdir=/home/alumno05
#SBATCH -J advanced
#SBATCH --cpus-per-task=4
#SBATCH --ntasks=4
#SBATCH --mail-type=NONE    #END/START/NONE
#SBATCH --mail-user=MAIL@um.es

module load anaconda/2023.03


time ipython reduc-operation-array_gpu-alumno05.ipynb 5000000
time ipython reduc-operation-array_gpu-alumno05.ipynb 50000000
time ipython reduc-operation-array_gpu-alumno05.ipynb 500000000

module unload anaconda/2023.03

